title: CV-Andrei-Martianov-Programmer
description: "Developer's CV"
baseurl: /CV-Andrei-Martianov-Programmer
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - docker-compose.yml
